version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672  
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: long
      RABBITMQ_DEFAULT_PASS: 3112
  db1:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=getsgo_user
  db2:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=getsgo_trip
  app1:
    depends_on:
      - db
      - rabbitmq
    restart: always
    build: ./UserService
    ports:
      - 3001:3001
    environment:
      - SECRET_KEY="supersecretkey"
      - DB_USN=root
      - DB_PWD=root
      - REDIS_CONN_STR=redis://redis:6379
      - MQ_URI=amqp://long:3112@rabbitmq
      - GOOGLE_APPLICATION_CREDENTIALS=./taxi-getgo-firebase-adminsdk-xg0mr-c58267b2c7.json
      - DB_NAME=getsgo_user
      - DB_PORT=3306
      - HOST=db
  app2:
    depends_on:
      - db1
      - rabbitmq
    restart: always
    build: ./TripService
    ports:
      - 3002:3002
    environment:
      - SECRET_KEY="supersecretkey"
      - DB_USN=root
      - DB_PWD=root
      - REDIS_CONN_STR=redis://redis:6379
      - MQ_URI=amqp://long:3112@rabbitmq
      - GOOGLE_APPLICATION_CREDENTIALS=./taxi-getgo-firebase-adminsdk-xg0mr-c58267b2c7.json
      - DB_NAME=getsgo_trip
      - DB_PORT=3307
      - HOST=db1
  app3:
    depends_on:
      - rabbitmq
    restart: always
    build: ./SocketService
    ports:
      - 3000:3000
    environment:
      - SECRET_KEY="supersecretkey"
      - GOOGLE_APPLICATION_CREDENTIALS=./taxi-getgo-firebase-adminsdk-xg0mr-c58267b2c7.json
      - MQ_URI=amqp://long:3112@rabbitmq
  app4:
    restart: always
    build: ./FirebaseMessaging
    ports:
      - 3004:3004
    environment:
      - SECRET_KEY="supersecretkey"
      - DB_USN=root
      - DB_PWD=root
      - REDIS_CONN_STR=redis://redis:6379
      - MQ_URI=amqp://long:3112@rabbitmq
      - GOOGLE_APPLICATION_CREDENTIALS=./taxi-getgo-firebase-adminsdk-xg0mr-c58267b2c7.json
      - DB_NAME=getsgo_user
      - DB_PORT=3306
      - HOST=db