###
POST http://localhost:3000/v1/users/signup
Content-Type: application/json

{
    "name":"Long",
    "phone":"+84555555555",
    "password":"123",
    "gender":"Male",
    "avatar":null
}

###
POST http://localhost:3000/v1/users/login
Content-Type: application/json

{
    "phone":"+84222222222",
    "password":"123"
}

###
POST http://localhost:3000/v1/booking/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicGhvbmUiOiIrODQ1NTU1NTU1NTUiLCJ0eXBlIjoiVXNlciIsImlhdCI6MTY4OTczNTkzOCwiZXhwIjoxNjkwODE1OTM4fQ.MHfErOG2zKjcLedIFxaLEfkzeFedlhiMEzkAcQl20fU
Content-Type: application/json

{
    "start":{
        "lat":10.1,
        "lng":10.2,
        "place":"random places"
    },
    "end":{
        "lat":10.3,
        "lng":10.4,
        "place":"2nd random places"
    },
    "is_scheduled":false,
    "price":50000,
    "is_paid":false,
    "payment_method":"Cash"
}

###
GET http://localhost:3000/v1/drivers/trips
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicGhvbmUiOiIrODQyMjIyMjIyMjIiLCJ0eXBlIjoiRHJpdmVyIiwiaWF0IjoxNjg5NzM1OTU5LCJleHAiOjE2OTA4MTU5NTl9.nfOtyA_7v1NgoFM5lTRurblnfP5n20QMTD-frVpUKG4

###
GET http://localhost:3000/v1/trips/1

###
PUT http://localhost:3000/v1/trips/1
Content-Type: application/json

{
    "status":"Confirmed"
}
